// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_template.proto

package com.example.tutorial;

public final class ProtoTemplate {
  private ProtoTemplate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string req_name = 1 [default = "nodes"];
    boolean hasReqName();
    String getReqName();
    
    // required .tutorial.KnowledgeBase kb = 2;
    boolean hasKb();
    com.example.tutorial.ProtoTemplate.KnowledgeBase getKb();
    com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder();
  }
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(Builder builder) {
      super(builder);
    }
    private Request(boolean noInit) {}
    
    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }
    
    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Request_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Request_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string req_name = 1 [default = "nodes"];
    public static final int REQ_NAME_FIELD_NUMBER = 1;
    private java.lang.Object reqName_;
    public boolean hasReqName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getReqName() {
      java.lang.Object ref = reqName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          reqName_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getReqNameBytes() {
      java.lang.Object ref = reqName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        reqName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .tutorial.KnowledgeBase kb = 2;
    public static final int KB_FIELD_NUMBER = 2;
    private com.example.tutorial.ProtoTemplate.KnowledgeBase kb_;
    public boolean hasKb() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.example.tutorial.ProtoTemplate.KnowledgeBase getKb() {
      return kb_;
    }
    public com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder() {
      return kb_;
    }
    
    private void initFields() {
      reqName_ = "nodes";
      kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getKb().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getReqNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, kb_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getReqNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, kb_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ProtoTemplate.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ProtoTemplate.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Request_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Request_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.ProtoTemplate.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKbFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        reqName_ = "nodes";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (kbBuilder_ == null) {
          kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
        } else {
          kbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ProtoTemplate.Request.getDescriptor();
      }
      
      public com.example.tutorial.ProtoTemplate.Request getDefaultInstanceForType() {
        return com.example.tutorial.ProtoTemplate.Request.getDefaultInstance();
      }
      
      public com.example.tutorial.ProtoTemplate.Request build() {
        com.example.tutorial.ProtoTemplate.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.ProtoTemplate.Request buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.ProtoTemplate.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.ProtoTemplate.Request buildPartial() {
        com.example.tutorial.ProtoTemplate.Request result = new com.example.tutorial.ProtoTemplate.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.reqName_ = reqName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (kbBuilder_ == null) {
          result.kb_ = kb_;
        } else {
          result.kb_ = kbBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ProtoTemplate.Request) {
          return mergeFrom((com.example.tutorial.ProtoTemplate.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.ProtoTemplate.Request other) {
        if (other == com.example.tutorial.ProtoTemplate.Request.getDefaultInstance()) return this;
        if (other.hasReqName()) {
          setReqName(other.getReqName());
        }
        if (other.hasKb()) {
          mergeKb(other.getKb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKb()) {
          
          return false;
        }
        if (!getKb().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              reqName_ = input.readBytes();
              break;
            }
            case 18: {
              com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder subBuilder = com.example.tutorial.ProtoTemplate.KnowledgeBase.newBuilder();
              if (hasKb()) {
                subBuilder.mergeFrom(getKb());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setKb(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string req_name = 1 [default = "nodes"];
      private java.lang.Object reqName_ = "nodes";
      public boolean hasReqName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getReqName() {
        java.lang.Object ref = reqName_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          reqName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setReqName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        reqName_ = value;
        onChanged();
        return this;
      }
      public Builder clearReqName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        reqName_ = getDefaultInstance().getReqName();
        onChanged();
        return this;
      }
      void setReqName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        reqName_ = value;
        onChanged();
      }
      
      // required .tutorial.KnowledgeBase kb = 2;
      private com.example.tutorial.ProtoTemplate.KnowledgeBase kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder> kbBuilder_;
      public boolean hasKb() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBase getKb() {
        if (kbBuilder_ == null) {
          return kb_;
        } else {
          return kbBuilder_.getMessage();
        }
      }
      public Builder setKb(com.example.tutorial.ProtoTemplate.KnowledgeBase value) {
        if (kbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kb_ = value;
          onChanged();
        } else {
          kbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setKb(
          com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder builderForValue) {
        if (kbBuilder_ == null) {
          kb_ = builderForValue.build();
          onChanged();
        } else {
          kbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeKb(com.example.tutorial.ProtoTemplate.KnowledgeBase value) {
        if (kbBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              kb_ != com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance()) {
            kb_ =
              com.example.tutorial.ProtoTemplate.KnowledgeBase.newBuilder(kb_).mergeFrom(value).buildPartial();
          } else {
            kb_ = value;
          }
          onChanged();
        } else {
          kbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearKb() {
        if (kbBuilder_ == null) {
          kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
          onChanged();
        } else {
          kbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder getKbBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getKbFieldBuilder().getBuilder();
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder() {
        if (kbBuilder_ != null) {
          return kbBuilder_.getMessageOrBuilder();
        } else {
          return kb_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder> 
          getKbFieldBuilder() {
        if (kbBuilder_ == null) {
          kbBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder>(
                  kb_,
                  getParentForChildren(),
                  isClean());
          kb_ = null;
        }
        return kbBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Request)
    }
    
    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Request)
  }
  
  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .tutorial.KnowledgeBase kb = 1;
    boolean hasKb();
    com.example.tutorial.ProtoTemplate.KnowledgeBase getKb();
    com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder();
    
    // required .tutorial.ClientState cs = 2;
    boolean hasCs();
    com.example.tutorial.ProtoTemplate.ClientState getCs();
    com.example.tutorial.ProtoTemplate.ClientStateOrBuilder getCsOrBuilder();
  }
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(Builder builder) {
      super(builder);
    }
    private Response(boolean noInit) {}
    
    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }
    
    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Response_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Response_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .tutorial.KnowledgeBase kb = 1;
    public static final int KB_FIELD_NUMBER = 1;
    private com.example.tutorial.ProtoTemplate.KnowledgeBase kb_;
    public boolean hasKb() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.example.tutorial.ProtoTemplate.KnowledgeBase getKb() {
      return kb_;
    }
    public com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder() {
      return kb_;
    }
    
    // required .tutorial.ClientState cs = 2;
    public static final int CS_FIELD_NUMBER = 2;
    private com.example.tutorial.ProtoTemplate.ClientState cs_;
    public boolean hasCs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.example.tutorial.ProtoTemplate.ClientState getCs() {
      return cs_;
    }
    public com.example.tutorial.ProtoTemplate.ClientStateOrBuilder getCsOrBuilder() {
      return cs_;
    }
    
    private void initFields() {
      kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
      cs_ = com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasKb()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getKb().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, kb_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, cs_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, kb_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, cs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ProtoTemplate.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ProtoTemplate.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Response_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Response_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.ProtoTemplate.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getKbFieldBuilder();
          getCsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (kbBuilder_ == null) {
          kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
        } else {
          kbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (csBuilder_ == null) {
          cs_ = com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance();
        } else {
          csBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ProtoTemplate.Response.getDescriptor();
      }
      
      public com.example.tutorial.ProtoTemplate.Response getDefaultInstanceForType() {
        return com.example.tutorial.ProtoTemplate.Response.getDefaultInstance();
      }
      
      public com.example.tutorial.ProtoTemplate.Response build() {
        com.example.tutorial.ProtoTemplate.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.ProtoTemplate.Response buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.ProtoTemplate.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.ProtoTemplate.Response buildPartial() {
        com.example.tutorial.ProtoTemplate.Response result = new com.example.tutorial.ProtoTemplate.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (kbBuilder_ == null) {
          result.kb_ = kb_;
        } else {
          result.kb_ = kbBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (csBuilder_ == null) {
          result.cs_ = cs_;
        } else {
          result.cs_ = csBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ProtoTemplate.Response) {
          return mergeFrom((com.example.tutorial.ProtoTemplate.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.ProtoTemplate.Response other) {
        if (other == com.example.tutorial.ProtoTemplate.Response.getDefaultInstance()) return this;
        if (other.hasKb()) {
          mergeKb(other.getKb());
        }
        if (other.hasCs()) {
          mergeCs(other.getCs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasKb()) {
          
          return false;
        }
        if (!hasCs()) {
          
          return false;
        }
        if (!getKb().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder subBuilder = com.example.tutorial.ProtoTemplate.KnowledgeBase.newBuilder();
              if (hasKb()) {
                subBuilder.mergeFrom(getKb());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setKb(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.example.tutorial.ProtoTemplate.ClientState.Builder subBuilder = com.example.tutorial.ProtoTemplate.ClientState.newBuilder();
              if (hasCs()) {
                subBuilder.mergeFrom(getCs());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCs(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .tutorial.KnowledgeBase kb = 1;
      private com.example.tutorial.ProtoTemplate.KnowledgeBase kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder> kbBuilder_;
      public boolean hasKb() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBase getKb() {
        if (kbBuilder_ == null) {
          return kb_;
        } else {
          return kbBuilder_.getMessage();
        }
      }
      public Builder setKb(com.example.tutorial.ProtoTemplate.KnowledgeBase value) {
        if (kbBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          kb_ = value;
          onChanged();
        } else {
          kbBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder setKb(
          com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder builderForValue) {
        if (kbBuilder_ == null) {
          kb_ = builderForValue.build();
          onChanged();
        } else {
          kbBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder mergeKb(com.example.tutorial.ProtoTemplate.KnowledgeBase value) {
        if (kbBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              kb_ != com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance()) {
            kb_ =
              com.example.tutorial.ProtoTemplate.KnowledgeBase.newBuilder(kb_).mergeFrom(value).buildPartial();
          } else {
            kb_ = value;
          }
          onChanged();
        } else {
          kbBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      public Builder clearKb() {
        if (kbBuilder_ == null) {
          kb_ = com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
          onChanged();
        } else {
          kbBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder getKbBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getKbFieldBuilder().getBuilder();
      }
      public com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder getKbOrBuilder() {
        if (kbBuilder_ != null) {
          return kbBuilder_.getMessageOrBuilder();
        } else {
          return kb_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder> 
          getKbFieldBuilder() {
        if (kbBuilder_ == null) {
          kbBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.tutorial.ProtoTemplate.KnowledgeBase, com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder, com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder>(
                  kb_,
                  getParentForChildren(),
                  isClean());
          kb_ = null;
        }
        return kbBuilder_;
      }
      
      // required .tutorial.ClientState cs = 2;
      private com.example.tutorial.ProtoTemplate.ClientState cs_ = com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.ClientState, com.example.tutorial.ProtoTemplate.ClientState.Builder, com.example.tutorial.ProtoTemplate.ClientStateOrBuilder> csBuilder_;
      public boolean hasCs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.example.tutorial.ProtoTemplate.ClientState getCs() {
        if (csBuilder_ == null) {
          return cs_;
        } else {
          return csBuilder_.getMessage();
        }
      }
      public Builder setCs(com.example.tutorial.ProtoTemplate.ClientState value) {
        if (csBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cs_ = value;
          onChanged();
        } else {
          csBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setCs(
          com.example.tutorial.ProtoTemplate.ClientState.Builder builderForValue) {
        if (csBuilder_ == null) {
          cs_ = builderForValue.build();
          onChanged();
        } else {
          csBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeCs(com.example.tutorial.ProtoTemplate.ClientState value) {
        if (csBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              cs_ != com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance()) {
            cs_ =
              com.example.tutorial.ProtoTemplate.ClientState.newBuilder(cs_).mergeFrom(value).buildPartial();
          } else {
            cs_ = value;
          }
          onChanged();
        } else {
          csBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearCs() {
        if (csBuilder_ == null) {
          cs_ = com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance();
          onChanged();
        } else {
          csBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.example.tutorial.ProtoTemplate.ClientState.Builder getCsBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getCsFieldBuilder().getBuilder();
      }
      public com.example.tutorial.ProtoTemplate.ClientStateOrBuilder getCsOrBuilder() {
        if (csBuilder_ != null) {
          return csBuilder_.getMessageOrBuilder();
        } else {
          return cs_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.example.tutorial.ProtoTemplate.ClientState, com.example.tutorial.ProtoTemplate.ClientState.Builder, com.example.tutorial.ProtoTemplate.ClientStateOrBuilder> 
          getCsFieldBuilder() {
        if (csBuilder_ == null) {
          csBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.example.tutorial.ProtoTemplate.ClientState, com.example.tutorial.ProtoTemplate.ClientState.Builder, com.example.tutorial.ProtoTemplate.ClientStateOrBuilder>(
                  cs_,
                  getParentForChildren(),
                  isClean());
          cs_ = null;
        }
        return csBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Response)
    }
    
    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Response)
  }
  
  public interface KnowledgeBaseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .tutorial.Node nodes = 1;
    java.util.List<com.example.tutorial.ProtoTemplate.Node> 
        getNodesList();
    com.example.tutorial.ProtoTemplate.Node getNodes(int index);
    int getNodesCount();
    java.util.List<? extends com.example.tutorial.ProtoTemplate.NodeOrBuilder> 
        getNodesOrBuilderList();
    com.example.tutorial.ProtoTemplate.NodeOrBuilder getNodesOrBuilder(
        int index);
  }
  public static final class KnowledgeBase extends
      com.google.protobuf.GeneratedMessage
      implements KnowledgeBaseOrBuilder {
    // Use KnowledgeBase.newBuilder() to construct.
    private KnowledgeBase(Builder builder) {
      super(builder);
    }
    private KnowledgeBase(boolean noInit) {}
    
    private static final KnowledgeBase defaultInstance;
    public static KnowledgeBase getDefaultInstance() {
      return defaultInstance;
    }
    
    public KnowledgeBase getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_KnowledgeBase_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_KnowledgeBase_fieldAccessorTable;
    }
    
    // repeated .tutorial.Node nodes = 1;
    public static final int NODES_FIELD_NUMBER = 1;
    private java.util.List<com.example.tutorial.ProtoTemplate.Node> nodes_;
    public java.util.List<com.example.tutorial.ProtoTemplate.Node> getNodesList() {
      return nodes_;
    }
    public java.util.List<? extends com.example.tutorial.ProtoTemplate.NodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    public int getNodesCount() {
      return nodes_.size();
    }
    public com.example.tutorial.ProtoTemplate.Node getNodes(int index) {
      return nodes_.get(index);
    }
    public com.example.tutorial.ProtoTemplate.NodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }
    
    private void initFields() {
      nodes_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getNodesCount(); i++) {
        if (!getNodes(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(1, nodes_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, nodes_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.KnowledgeBase parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ProtoTemplate.KnowledgeBase prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ProtoTemplate.KnowledgeBaseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_KnowledgeBase_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_KnowledgeBase_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.ProtoTemplate.KnowledgeBase.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ProtoTemplate.KnowledgeBase.getDescriptor();
      }
      
      public com.example.tutorial.ProtoTemplate.KnowledgeBase getDefaultInstanceForType() {
        return com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance();
      }
      
      public com.example.tutorial.ProtoTemplate.KnowledgeBase build() {
        com.example.tutorial.ProtoTemplate.KnowledgeBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.ProtoTemplate.KnowledgeBase buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.ProtoTemplate.KnowledgeBase result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.ProtoTemplate.KnowledgeBase buildPartial() {
        com.example.tutorial.ProtoTemplate.KnowledgeBase result = new com.example.tutorial.ProtoTemplate.KnowledgeBase(this);
        int from_bitField0_ = bitField0_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ProtoTemplate.KnowledgeBase) {
          return mergeFrom((com.example.tutorial.ProtoTemplate.KnowledgeBase)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.ProtoTemplate.KnowledgeBase other) {
        if (other == com.example.tutorial.ProtoTemplate.KnowledgeBase.getDefaultInstance()) return this;
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getNodesCount(); i++) {
          if (!getNodes(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              com.example.tutorial.ProtoTemplate.Node.Builder subBuilder = com.example.tutorial.ProtoTemplate.Node.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addNodes(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .tutorial.Node nodes = 1;
      private java.util.List<com.example.tutorial.ProtoTemplate.Node> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          nodes_ = new java.util.ArrayList<com.example.tutorial.ProtoTemplate.Node>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.ProtoTemplate.Node, com.example.tutorial.ProtoTemplate.Node.Builder, com.example.tutorial.ProtoTemplate.NodeOrBuilder> nodesBuilder_;
      
      public java.util.List<com.example.tutorial.ProtoTemplate.Node> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      public com.example.tutorial.ProtoTemplate.Node getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      public Builder setNodes(
          int index, com.example.tutorial.ProtoTemplate.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setNodes(
          int index, com.example.tutorial.ProtoTemplate.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(com.example.tutorial.ProtoTemplate.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addNodes(
          int index, com.example.tutorial.ProtoTemplate.Node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addNodes(
          com.example.tutorial.ProtoTemplate.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addNodes(
          int index, com.example.tutorial.ProtoTemplate.Node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.example.tutorial.ProtoTemplate.Node> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          super.addAll(values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      public com.example.tutorial.ProtoTemplate.Node.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      public com.example.tutorial.ProtoTemplate.NodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.example.tutorial.ProtoTemplate.NodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      public com.example.tutorial.ProtoTemplate.Node.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.example.tutorial.ProtoTemplate.Node.getDefaultInstance());
      }
      public com.example.tutorial.ProtoTemplate.Node.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.example.tutorial.ProtoTemplate.Node.getDefaultInstance());
      }
      public java.util.List<com.example.tutorial.ProtoTemplate.Node.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.example.tutorial.ProtoTemplate.Node, com.example.tutorial.ProtoTemplate.Node.Builder, com.example.tutorial.ProtoTemplate.NodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.example.tutorial.ProtoTemplate.Node, com.example.tutorial.ProtoTemplate.Node.Builder, com.example.tutorial.ProtoTemplate.NodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.KnowledgeBase)
    }
    
    static {
      defaultInstance = new KnowledgeBase(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.KnowledgeBase)
  }
  
  public interface ClientStateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string action = 1;
    java.util.List<String> getActionList();
    int getActionCount();
    String getAction(int index);
  }
  public static final class ClientState extends
      com.google.protobuf.GeneratedMessage
      implements ClientStateOrBuilder {
    // Use ClientState.newBuilder() to construct.
    private ClientState(Builder builder) {
      super(builder);
    }
    private ClientState(boolean noInit) {}
    
    private static final ClientState defaultInstance;
    public static ClientState getDefaultInstance() {
      return defaultInstance;
    }
    
    public ClientState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_ClientState_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_ClientState_fieldAccessorTable;
    }
    
    // repeated string action = 1;
    public static final int ACTION_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList action_;
    public java.util.List<String>
        getActionList() {
      return action_;
    }
    public int getActionCount() {
      return action_.size();
    }
    public String getAction(int index) {
      return action_.get(index);
    }
    
    private void initFields() {
      action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < action_.size(); i++) {
        output.writeBytes(1, action_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < action_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(action_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getActionList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.ClientState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ProtoTemplate.ClientState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ProtoTemplate.ClientStateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_ClientState_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_ClientState_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.ProtoTemplate.ClientState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ProtoTemplate.ClientState.getDescriptor();
      }
      
      public com.example.tutorial.ProtoTemplate.ClientState getDefaultInstanceForType() {
        return com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance();
      }
      
      public com.example.tutorial.ProtoTemplate.ClientState build() {
        com.example.tutorial.ProtoTemplate.ClientState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.ProtoTemplate.ClientState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.ProtoTemplate.ClientState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.ProtoTemplate.ClientState buildPartial() {
        com.example.tutorial.ProtoTemplate.ClientState result = new com.example.tutorial.ProtoTemplate.ClientState(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          action_ = new com.google.protobuf.UnmodifiableLazyStringList(
              action_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.action_ = action_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ProtoTemplate.ClientState) {
          return mergeFrom((com.example.tutorial.ProtoTemplate.ClientState)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.ProtoTemplate.ClientState other) {
        if (other == com.example.tutorial.ProtoTemplate.ClientState.getDefaultInstance()) return this;
        if (!other.action_.isEmpty()) {
          if (action_.isEmpty()) {
            action_ = other.action_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureActionIsMutable();
            action_.addAll(other.action_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureActionIsMutable();
              action_.add(input.readBytes());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string action = 1;
      private com.google.protobuf.LazyStringList action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureActionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          action_ = new com.google.protobuf.LazyStringArrayList(action_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getActionList() {
        return java.util.Collections.unmodifiableList(action_);
      }
      public int getActionCount() {
        return action_.size();
      }
      public String getAction(int index) {
        return action_.get(index);
      }
      public Builder setAction(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addAction(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActionIsMutable();
        action_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllAction(
          java.lang.Iterable<String> values) {
        ensureActionIsMutable();
        super.addAll(values, action_);
        onChanged();
        return this;
      }
      public Builder clearAction() {
        action_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addAction(com.google.protobuf.ByteString value) {
        ensureActionIsMutable();
        action_.add(value);
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.ClientState)
    }
    
    static {
      defaultInstance = new ClientState(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.ClientState)
  }
  
  public interface NodeOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string node_id = 1;
    boolean hasNodeId();
    String getNodeId();
    
    // optional int32 cpu = 2;
    boolean hasCpu();
    int getCpu();
    
    // optional int32 heap = 3;
    boolean hasHeap();
    int getHeap();
  }
  public static final class Node extends
      com.google.protobuf.GeneratedMessage
      implements NodeOrBuilder {
    // Use Node.newBuilder() to construct.
    private Node(Builder builder) {
      super(builder);
    }
    private Node(boolean noInit) {}
    
    private static final Node defaultInstance;
    public static Node getDefaultInstance() {
      return defaultInstance;
    }
    
    public Node getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Node_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Node_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string node_id = 1;
    public static final int NODE_ID_FIELD_NUMBER = 1;
    private java.lang.Object nodeId_;
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNodeId() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          nodeId_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNodeIdBytes() {
      java.lang.Object ref = nodeId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        nodeId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int32 cpu = 2;
    public static final int CPU_FIELD_NUMBER = 2;
    private int cpu_;
    public boolean hasCpu() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getCpu() {
      return cpu_;
    }
    
    // optional int32 heap = 3;
    public static final int HEAP_FIELD_NUMBER = 3;
    private int heap_;
    public boolean hasHeap() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getHeap() {
      return heap_;
    }
    
    private void initFields() {
      nodeId_ = "";
      cpu_ = 0;
      heap_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, heap_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNodeIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cpu_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, heap_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Node parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.example.tutorial.ProtoTemplate.Node parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.example.tutorial.ProtoTemplate.Node prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.example.tutorial.ProtoTemplate.NodeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Node_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.tutorial.ProtoTemplate.internal_static_tutorial_Node_fieldAccessorTable;
      }
      
      // Construct using com.example.tutorial.ProtoTemplate.Node.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        nodeId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        cpu_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        heap_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.tutorial.ProtoTemplate.Node.getDescriptor();
      }
      
      public com.example.tutorial.ProtoTemplate.Node getDefaultInstanceForType() {
        return com.example.tutorial.ProtoTemplate.Node.getDefaultInstance();
      }
      
      public com.example.tutorial.ProtoTemplate.Node build() {
        com.example.tutorial.ProtoTemplate.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.example.tutorial.ProtoTemplate.Node buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.example.tutorial.ProtoTemplate.Node result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.example.tutorial.ProtoTemplate.Node buildPartial() {
        com.example.tutorial.ProtoTemplate.Node result = new com.example.tutorial.ProtoTemplate.Node(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cpu_ = cpu_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.heap_ = heap_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.tutorial.ProtoTemplate.Node) {
          return mergeFrom((com.example.tutorial.ProtoTemplate.Node)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.example.tutorial.ProtoTemplate.Node other) {
        if (other == com.example.tutorial.ProtoTemplate.Node.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (other.hasCpu()) {
          setCpu(other.getCpu());
        }
        if (other.hasHeap()) {
          setHeap(other.getHeap());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNodeId()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cpu_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              heap_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string node_id = 1;
      private java.lang.Object nodeId_ = "";
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNodeId() {
        java.lang.Object ref = nodeId_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          nodeId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNodeId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = getDefaultInstance().getNodeId();
        onChanged();
        return this;
      }
      void setNodeId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
      }
      
      // optional int32 cpu = 2;
      private int cpu_ ;
      public boolean hasCpu() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCpu() {
        return cpu_;
      }
      public Builder setCpu(int value) {
        bitField0_ |= 0x00000002;
        cpu_ = value;
        onChanged();
        return this;
      }
      public Builder clearCpu() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cpu_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 heap = 3;
      private int heap_ ;
      public boolean hasHeap() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getHeap() {
        return heap_;
      }
      public Builder setHeap(int value) {
        bitField0_ |= 0x00000004;
        heap_ = value;
        onChanged();
        return this;
      }
      public Builder clearHeap() {
        bitField0_ = (bitField0_ & ~0x00000004);
        heap_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tutorial.Node)
    }
    
    static {
      defaultInstance = new Node(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tutorial.Node)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_KnowledgeBase_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_KnowledgeBase_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_ClientState_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_ClientState_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tutorial_Node_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tutorial_Node_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024proto_template.proto\022\010tutorial\"G\n\007Requ" +
      "est\022\027\n\010req_name\030\001 \001(\t:\005nodes\022#\n\002kb\030\002 \002(\013" +
      "2\027.tutorial.KnowledgeBase\"R\n\010Response\022#\n" +
      "\002kb\030\001 \002(\0132\027.tutorial.KnowledgeBase\022!\n\002cs" +
      "\030\002 \002(\0132\025.tutorial.ClientState\".\n\rKnowled" +
      "geBase\022\035\n\005nodes\030\001 \003(\0132\016.tutorial.Node\"\035\n" +
      "\013ClientState\022\016\n\006action\030\001 \003(\t\"2\n\004Node\022\017\n\007" +
      "node_id\030\001 \002(\t\022\013\n\003cpu\030\002 \001(\005\022\014\n\004heap\030\003 \001(\005" +
      "B%\n\024com.example.tutorialB\rProtoTemplate"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tutorial_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tutorial_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Request_descriptor,
              new java.lang.String[] { "ReqName", "Kb", },
              com.example.tutorial.ProtoTemplate.Request.class,
              com.example.tutorial.ProtoTemplate.Request.Builder.class);
          internal_static_tutorial_Response_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tutorial_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Response_descriptor,
              new java.lang.String[] { "Kb", "Cs", },
              com.example.tutorial.ProtoTemplate.Response.class,
              com.example.tutorial.ProtoTemplate.Response.Builder.class);
          internal_static_tutorial_KnowledgeBase_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tutorial_KnowledgeBase_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_KnowledgeBase_descriptor,
              new java.lang.String[] { "Nodes", },
              com.example.tutorial.ProtoTemplate.KnowledgeBase.class,
              com.example.tutorial.ProtoTemplate.KnowledgeBase.Builder.class);
          internal_static_tutorial_ClientState_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_tutorial_ClientState_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_ClientState_descriptor,
              new java.lang.String[] { "Action", },
              com.example.tutorial.ProtoTemplate.ClientState.class,
              com.example.tutorial.ProtoTemplate.ClientState.Builder.class);
          internal_static_tutorial_Node_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_tutorial_Node_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_tutorial_Node_descriptor,
              new java.lang.String[] { "NodeId", "Cpu", "Heap", },
              com.example.tutorial.ProtoTemplate.Node.class,
              com.example.tutorial.ProtoTemplate.Node.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
