// Generated by http://code.google.com/p/protostuff/ ... DO NOT EDIT!
// Generated from nodes.proto

package com.example.tutorial;


public final class SchemaNodeProtos
{

    public static final class Request
    {
        public static final com.example.tutorial.SchemaNodeProtos.Request.MessageSchema WRITE =
            new com.example.tutorial.SchemaNodeProtos.Request.MessageSchema();
        public static final com.example.tutorial.SchemaNodeProtos.Request.BuilderSchema MERGE =
            new com.example.tutorial.SchemaNodeProtos.Request.BuilderSchema();
        
        public static class MessageSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Request>
        {
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Request message) throws java.io.IOException
            {
                if(message.hasReqName())
                    output.writeString(1, message.getReqName(), false);
                for(com.example.tutorial.NodeProtos.Node nodes : message.getNodesList())
                    output.writeObject(2, nodes, com.example.tutorial.SchemaNodeProtos.Node.WRITE, true);

            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Request message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Request.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Request.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Request> typeClass()
            {
                return com.example.tutorial.NodeProtos.Request.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Request.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Request.class.getName();
            }
            //unused
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Request message) throws java.io.IOException {}
            public com.example.tutorial.NodeProtos.Request newMessage() { return null; }
        }
        public static class BuilderSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Request.Builder>
        {
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Request.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setReqName(input.readString());
                            break;
                        case 2:
                            builder.addNodes(input.mergeObject(com.example.tutorial.NodeProtos.Node.newBuilder(), com.example.tutorial.SchemaNodeProtos.Node.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Request.Builder builder)
            {
                return builder.isInitialized();
            }
            public com.example.tutorial.NodeProtos.Request.Builder newMessage()
            {
                return com.example.tutorial.NodeProtos.Request.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Request.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Request.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Request.Builder> typeClass()
            {
                return com.example.tutorial.NodeProtos.Request.Builder.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Request.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Request.class.getName();
            }
            //unused
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Request.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            return java.lang.String.valueOf(number);
        }
        public static int getFieldNumber(java.lang.String name)
        {
            return java.lang.Integer.parseInt(name);
        }

    }

    public static final class Response
    {
        public static final com.example.tutorial.SchemaNodeProtos.Response.MessageSchema WRITE =
            new com.example.tutorial.SchemaNodeProtos.Response.MessageSchema();
        public static final com.example.tutorial.SchemaNodeProtos.Response.BuilderSchema MERGE =
            new com.example.tutorial.SchemaNodeProtos.Response.BuilderSchema();
        
        public static class MessageSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Response>
        {
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Response message) throws java.io.IOException
            {
                for(String action : message.getActionList())
                    output.writeString(1, action, true);
                for(com.example.tutorial.NodeProtos.Node nodes : message.getNodesList())
                    output.writeObject(2, nodes, com.example.tutorial.SchemaNodeProtos.Node.WRITE, true);

            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Response message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Response.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Response.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Response> typeClass()
            {
                return com.example.tutorial.NodeProtos.Response.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Response.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Response.class.getName();
            }
            //unused
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Response message) throws java.io.IOException {}
            public com.example.tutorial.NodeProtos.Response newMessage() { return null; }
        }
        public static class BuilderSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Response.Builder>
        {
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Response.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.addAction(input.readString());
                            break;
                        case 2:
                            builder.addNodes(input.mergeObject(com.example.tutorial.NodeProtos.Node.newBuilder(), com.example.tutorial.SchemaNodeProtos.Node.MERGE));

                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Response.Builder builder)
            {
                return builder.isInitialized();
            }
            public com.example.tutorial.NodeProtos.Response.Builder newMessage()
            {
                return com.example.tutorial.NodeProtos.Response.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Response.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Response.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Response.Builder> typeClass()
            {
                return com.example.tutorial.NodeProtos.Response.Builder.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Response.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Response.class.getName();
            }
            //unused
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Response.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            return java.lang.String.valueOf(number);
        }
        public static int getFieldNumber(java.lang.String name)
        {
            return java.lang.Integer.parseInt(name);
        }

    }

    public static final class Node
    {
        public static final com.example.tutorial.SchemaNodeProtos.Node.MessageSchema WRITE =
            new com.example.tutorial.SchemaNodeProtos.Node.MessageSchema();
        public static final com.example.tutorial.SchemaNodeProtos.Node.BuilderSchema MERGE =
            new com.example.tutorial.SchemaNodeProtos.Node.BuilderSchema();
        
        public static class MessageSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Node>
        {
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Node message) throws java.io.IOException
            {
                if(message.hasNodeId())
                    output.writeString(1, message.getNodeId(), false);
                if(message.hasCpu())
                    output.writeInt32(2, message.getCpu(), false);
                if(message.hasHeap())
                    output.writeInt32(3, message.getHeap(), false);
            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Node message)
            {
                return message.isInitialized();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Node.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Node.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Node> typeClass()
            {
                return com.example.tutorial.NodeProtos.Node.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Node.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Node.class.getName();
            }
            //unused
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Node message) throws java.io.IOException {}
            public com.example.tutorial.NodeProtos.Node newMessage() { return null; }
        }
        public static class BuilderSchema implements com.dyuproject.protostuff.Schema<com.example.tutorial.NodeProtos.Node.Builder>
        {
            public void mergeFrom(com.dyuproject.protostuff.Input input, com.example.tutorial.NodeProtos.Node.Builder builder) throws java.io.IOException
            {
                for(int number = input.readFieldNumber(this);; number = input.readFieldNumber(this))
                {
                    switch(number)
                    {
                        case 0:
                            return;
                        case 1:
                            builder.setNodeId(input.readString());
                            break;
                        case 2:
                            builder.setCpu(input.readInt32());
                            break;
                        case 3:
                            builder.setHeap(input.readInt32());
                            break;
                        default:
                            input.handleUnknownField(number, this);
                    }
                }
            }
            public boolean isInitialized(com.example.tutorial.NodeProtos.Node.Builder builder)
            {
                return builder.isInitialized();
            }
            public com.example.tutorial.NodeProtos.Node.Builder newMessage()
            {
                return com.example.tutorial.NodeProtos.Node.newBuilder();
            }
            public java.lang.String getFieldName(int number)
            {
                return com.example.tutorial.SchemaNodeProtos.Node.getFieldName(number);
            }
            public int getFieldNumber(java.lang.String name)
            {
                return com.example.tutorial.SchemaNodeProtos.Node.getFieldNumber(name);
            }
            public java.lang.Class<com.example.tutorial.NodeProtos.Node.Builder> typeClass()
            {
                return com.example.tutorial.NodeProtos.Node.Builder.class;
            }
            public java.lang.String messageName()
            {
                return com.example.tutorial.NodeProtos.Node.class.getSimpleName();
            }
            public java.lang.String messageFullName()
            {
                return com.example.tutorial.NodeProtos.Node.class.getName();
            }
            //unused
            public void writeTo(com.dyuproject.protostuff.Output output, com.example.tutorial.NodeProtos.Node.Builder builder) throws java.io.IOException {}
        }
        public static java.lang.String getFieldName(int number)
        {
            return java.lang.String.valueOf(number);
        }
        public static int getFieldNumber(java.lang.String name)
        {
            return java.lang.Integer.parseInt(name);
        }

    }

}
